/** JARVIS V9 core controller — stable WebSocket Home Assistant transport. */
(()=>{'use strict';
const KEY='jarvis_v9_settings';
const state={connection:{url:'',token:'',status:'disconnected',error:''},menu:{open:false,category:null,selected:[]},settings:{account:{},voice:{},system:{},general:{}},log:[],listeners:new Set(),socket:null,seq:0,pending:new Map()};
const snapshot=()=>({connection:{url:state.connection.url,status:state.connection.status,error:state.connection.error,token:undefined},menu:{...state.menu,selected:[...state.menu.selected]},settings:structuredClone(state.settings),log:[...state.log]});
const emit=name=>window.dispatchEvent(new CustomEvent(name,{detail:snapshot()}));
const notify=()=>state.listeners.forEach(fn=>{try{fn(snapshot())}catch(_){}});
const log=(level,message,data)=>{const entry={time:new Date().toISOString(),level,message:String(message),...(data===undefined?{}:{data})};state.log.push(entry);if(state.log.length>300)state.log.splice(0,state.log.length-300);window.dispatchEvent(new CustomEvent('jarvis:v9:log',{detail:entry}));notify();return entry};
function loadSettings(){try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(p&&typeof p==='object')state.settings={...state.settings,...p}}}catch(_){}}
function saveSettings(){try{localStorage.setItem(KEY,JSON.stringify(state.settings))}catch(_){}emit('jarvis:v9-settings-changed');notify()}
const normalizeUrl=url=>String(url||'').trim().replace(/\/$/,'');
const wsUrl=url=>{const u=normalizeUrl(url);return u.replace(/^https:/i,'wss:').replace(/^http:/i,'ws:')+'/api/websocket'};
function closeSocket(reason='Connexion fermée'){const s=state.socket;state.socket=null;if(s){try{s.close()}catch(_){}}for(const [,p] of state.pending){try{p.reject(new Error(reason))}catch(_){}}state.pending.clear()}
function openSocket(url,token){return new Promise((resolve,reject)=>{let done=false,authenticated=false;const s=new WebSocket(wsUrl(url));state.socket=s;const finishReject=msg=>{if(done)return;done=true;clearTimeout(timer);reject(new Error(msg))};const timer=setTimeout(()=>{try{s.close()}catch(_){};finishReject('WebSocket Home Assistant : délai dépassé')},12000);s.onopen=()=>{};s.onerror=()=>finishReject('WebSocket Home Assistant indisponible');s.onclose=()=>{if(state.socket===s)state.socket=null;if(!authenticated)finishReject('WebSocket Home Assistant fermé avant authentification')};s.onmessage=event=>{let m;try{m=JSON.parse(event.data)}catch(_){return}
if(m.type==='auth_required'){try{s.send(JSON.stringify({type:'auth',access_token:token}))}catch(_){finishReject('Impossible d’envoyer le token Home Assistant')}return}
if(m.type==='auth_ok'){authenticated=true;if(!done){done=true;clearTimeout(timer);resolve(s)}return}
if(m.type==='auth_invalid'){finishReject('Token Home Assistant refusé');try{s.close()}catch(_){};return}
if(m.type==='result'&&m.id!=null){const p=state.pending.get(m.id);if(!p)return;state.pending.delete(m.id);m.success?p.resolve(m.result):p.reject(new Error(m.error?.message||'Commande Home Assistant refusée'))}
}})})}
async function wsRequest(path,options={}){const s=state.socket;if(!s||s.readyState!==WebSocket.OPEN)throw new Error('Connexion WebSocket Home Assistant non disponible');const clean=String(path||'');const method=String(options.method||'GET').toUpperCase();let message;
if(clean==='/api/'&&method==='GET')message={type:'get_config'};
else if(clean==='/api/states'&&method==='GET')message={type:'get_states'};
else if(clean==='/api/services'&&method==='GET')message={type:'get_services'};
else if(/^\/api\/services\/[^/]+\/[^/]+$/.test(clean)&&method==='POST'){const p=clean.split('/');let data={};try{data=options.body?JSON.parse(options.body):{}}catch(_){}message={type:'call_service',domain:decodeURIComponent(p[3]),service:decodeURIComponent(p[4]),service_data:data};}
else throw new Error(`API Home Assistant non supportée via WebSocket : ${clean}`);
const id=++state.seq;message.id=id;return new Promise((resolve,reject)=>{state.pending.set(id,{resolve,reject});try{s.send(JSON.stringify(message))}catch(e){state.pending.delete(id);reject(e)}})}
async function connect(url,token){const nextUrl=normalizeUrl(url),nextToken=String(token||'').trim();if(!/^https?:\/\//i.test(nextUrl)||!nextToken)throw new Error('URL et token Home Assistant requis');closeSocket();state.connection={url:nextUrl,token:nextToken,status:'connecting',error:''};emit('jarvis:v9-connection');notify();try{await openSocket(nextUrl,nextToken);state.connection.status='connected';state.connection.error='';state.settings.account.url=nextUrl;saveSettings();log('info','Home Assistant connecté via WebSocket');emit('jarvis:v9-connection');notify();setTimeout(async()=>{try{const runtime=window.JARVIS_V9_RUNTIME;if(runtime){runtime.setConnection({request:wsRequest});await runtime.refreshEntities()}}catch(e){log('warn','Actualisation des entités V9 impossible',e.message)}},0);return true}catch(e){closeSocket(e.message);state.connection.status='error';state.connection.error=e.message;log('error','Échec de connexion Home Assistant',e.message);emit('jarvis:v9-connection');notify();throw e}}
const adoptConnection=connect;
function disconnect(){closeSocket();state.connection={url:'',token:'',status:'disconnected',error:''};window.JARVIS_V9_RUNTIME?.clearConnection?.();log('info','Connexion Home Assistant fermée');emit('jarvis:v9-connection');notify()}
const api=Object.freeze({version:'9.0-ws',connect,adoptConnection,disconnect,request:wsRequest,getConnection:()=>({...state.connection,token:undefined}),getSecretToken:()=>state.connection.token,getLog:()=>[...state.log],clearLog:()=>{state.log.length=0;notify()},copyLog:async()=>{const t=state.log.map(e=>`[${e.time}] ${e.level.toUpperCase()} ${e.message}`).join('\n');if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(t)},log,getMenu:()=>({...state.menu,selected:[...state.menu.selected]}),setCategory:(id,selected=[])=>{state.menu.category=id;state.menu.selected=[...selected];emit('jarvis:v9-menu-changed');notify()},clearSelection:()=>{state.menu.category=null;state.menu.selected=[];notify()},setOpen:open=>{state.menu.open=!!open;notify()},readSettings:()=>structuredClone(state.settings),setSetting:(section,key,value)=>{if(key==='token'||key==='accessToken')throw new Error('Les secrets ne sont pas stockés dans les réglages V9');state.settings[section]??={};state.settings[section][key]=value;saveSettings()},subscribe:fn=>{state.listeners.add(fn);return()=>state.listeners.delete(fn)}});
loadSettings();window.JARVIS_V9_CORE=api;window.JARVIS_V9_MENU=Object.freeze({read:api.getMenu,setCategory:api.setCategory,clear:api.clearSelection,open:()=>api.setOpen(true),close:()=>api.setOpen(false)});window.JARVIS_V9_SETTINGS=Object.freeze({read:api.readSettings,set:api.setSetting});window.dispatchEvent(new CustomEvent('jarvis:v9-core-ready'));})();
