const DEFAULTS={theme:'classic',coreSize:100,motion:'normal',blocks:{energy:'under',home:'under',export:'under',security:'under'},orbit:{activity:true,events:true,presence:true,openings:true,energy:true,climate:true,voice:false,security:true,sentinel:true,network:false,vehicle:false,memory:false},activeMenu:'home'};
const clone=o=>JSON.parse(JSON.stringify(o));
let saved=clone(DEFAULTS);try{const x=JSON.parse(localStorage.getItem('jarvis_v41_preview')||'null');if(x)saved={...clone(DEFAULTS),...x,blocks:{...DEFAULTS.blocks,...(x.blocks||{})},orbit:{...DEFAULTS.orbit,...(x.orbit||{})}}}catch(e){}
let draft=clone(saved),dirty=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const liveCss=document.createElement('link');liveCss.rel='stylesheet';liveCss.href='live.css?v=41v';document.head.appendChild(liveCss);
const themeMap={classic:'#00eaff',holo:'#4a8dff',sentinel:'#ff8b36',glass:'#b36cff',neural:'#42ffd6'};
const themeNames={classic:'Classic HUD',holo:'Holo Grid',sentinel:'Sentinel Tactical',glass:'Glass Orbital',neural:'Neural Core'};
const motionMap={low:.65,normal:1,high:1.35};
const leftHud=$('.sidehud.left'),rightHud=$('.sidehud.right');
if(leftHud){leftHud.insertAdjacentHTML('afterbegin',`<div class="sidebox orbit-card live" data-orbit="presence"><b>PRÉSENCE</b><div class="live-row"><span>2 présents</span><i class="live-dot"></i></div><small class="live-sub">Maison occupée</small></div><div class="sidebox orbit-card live alert" data-orbit="openings"><b>OUVERTURES</b><div class="live-row"><span>1 ouverte</span><i class="live-dot alert"></i></div><small class="live-sub">Porte garage ouverte</small></div>`)}
if(leftHud){leftHud.insertAdjacentHTML('beforeend',`<div class="sidebox orbit-card live" data-orbit="climate"><b>CONFORT</b><div class="live-row"><span>19.8 °C</span><i class="live-dot"></i></div><small class="live-sub">Salon · consigne 19°</small></div>`)}
if(rightHud){rightHud.insertAdjacentHTML('beforeend',`<div class="sidebox orbit-card live" data-orbit="vehicle"><b>VÉHICULE</b><div class="live-row"><span>Absent</span><i class="live-dot warn"></i></div><small class="live-sub">e-208 non détectée</small></div>`)}
const online=$('.online');if(online)online.insertAdjacentHTML('afterend','<div class="realtime-strip"><i></i><b>TEMPS RÉEL</b><span id="liveClock">MAJ --:--:--</span></div>');
const orbitSelect=$('#orbitSelect');if(orbitSelect){orbitSelect.insertAdjacentHTML('afterbegin',`<button class="orbit-toggle" data-orbit-key="presence"><b>Présence</b><small>Qui est à la maison</small></button><button class="orbit-toggle" data-orbit-key="openings"><b>Ouvertures</b><small>Portes / fenêtres</small></button>`);orbitSelect.insertAdjacentHTML('beforeend',`<button class="orbit-toggle" data-orbit-key="climate"><b>Confort</b><small>Température / consigne</small></button><button class="orbit-toggle" data-orbit-key="vehicle"><b>Véhicule</b><small>Présence / charge</small></button>`);const note=orbitSelect.parentElement?.querySelector('.landscape-note');if(note)note.insertAdjacentHTML('afterend','<div class="priority-note"><strong>Infos prioritaires</strong> · En paysage, les cartes sélectionnées sont réparties autour du Core.</div>')}
const ticks=$('#ticks');for(let i=0;i<72;i++){const e=document.createElement('i');e.className='tick'+(i%6===0?' major':'');e.style.transform=`rotate(${i*5}deg) translateY(-176px)`;ticks.appendChild(e)}
const open=id=>$('#'+id).classList.add('open');const close=id=>$('#'+id).classList.remove('open');
$('#openMenu').onclick=()=>open('menuPanel');$('#menuBtn').onclick=()=>open('menuPanel');$('#settingsBtn').onclick=()=>open('settingsPanel');$('#appearanceBtn').onclick=()=>{open('settingsPanel');selectPane('core')};$('#voiceBtn').onclick=()=>{open('settingsPanel');selectPane('voice')};$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
function selectPane(name){$$('#settingsNav button').forEach(x=>x.classList.toggle('active',x.dataset.pane===name));$$('.settings-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===name))}$$('#settingsNav button').forEach(b=>b.onclick=()=>selectPane(b.dataset.pane));
function persist(){localStorage.setItem('jarvis_v41_preview',JSON.stringify(saved))}
function setMenu(cat){saved.activeMenu=cat;persist();$$('#menuTabs button').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));$$('#menuCards .card').forEach(c=>c.hidden=c.dataset.cat!==cat);renderMenuOnly()}$$('#menuTabs button').forEach(b=>b.onclick=()=>setMenu(b.dataset.cat));
const themesBox=$('#themes');Object.keys(themeMap).forEach(k=>{const b=document.createElement('button');b.className='theme';b.dataset.theme=k;b.innerHTML=`<div class="preview"></div><strong>${themeNames[k]}</strong>`;b.onclick=()=>{draft.theme=k;markDirty();renderDraft()};themesBox.appendChild(b)});

/* Core controls: injected in the Core settings so the preview can be tuned live. */
const corePane=$('.settings-pane[data-pane="core"]');if(corePane){const first=corePane.querySelector('.section');const sec=document.createElement('div');sec.className='section core-live-controls';sec.innerHTML=`<div class="title">TAILLE & MOUVEMENT DU CORE</div><div class="core-control"><div><b>Taille du Core</b><small>Aperçu instantané · 75 à 130%</small></div><div class="size-line"><input id="coreSize" type="range" min="75" max="130" step="1"><output id="coreSizeValue">100%</output></div><div class="core-presets"><button data-size="85">Petit</button><button data-size="100">Normal</button><button data-size="115">Grand</button><button data-size="130">XL</button></div></div><div class="core-control"><div><b>Intensité des animations</b><small>Adapte aussi le rendu en paysage</small></div><div class="motion-choice"><button data-motion="low">Faible</button><button data-motion="normal">Normale</button><button data-motion="high">Élevée</button></div></div><button class="state-test" id="stateTest">TESTER LES ÉTATS DU CORE</button><div class="state-readout" id="stateReadout">État : OPÉRATIONNEL</div>`;first?.after(sec)}
const uiStyle=document.createElement('style');uiStyle.textContent=`.core-live-controls .core-control{padding:10px 0;border-bottom:1px solid #00eaff10}.core-live-controls b{font-size:10px}.core-live-controls small{display:block;margin-top:3px;color:#6b91a0;font-size:8px}.size-line{display:grid;grid-template-columns:1fr 54px;gap:10px;align-items:center;margin-top:10px}.size-line input{width:100%;accent-color:var(--a)}.size-line output{height:32px;display:grid;place-items:center;border:1px solid #00eaff28;border-radius:9px;background:#03131d;font:9px monospace;color:#dffaff}.core-presets,.motion-choice{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.motion-choice{grid-template-columns:repeat(3,1fr)}.core-presets button,.motion-choice button,.state-test{min-height:34px;border:1px solid #00eaff22;border-radius:9px;background:#04131e;color:#87aab7;font-size:8px}.core-presets button.on,.motion-choice button.on{border-color:#00eaff66;background:#0a2d40;color:#efffff}.state-test{width:100%;margin-top:12px;color:#c9fbff}.state-readout{text-align:center;margin-top:7px;color:#6f9eae;font:8px monospace;letter-spacing:1px}`;document.head.appendChild(uiStyle);
function markDirty(){dirty=true;$('#saveBtn').classList.add('dirty')}
function applyCoreTuning(cfg){const size=Math.max(75,Math.min(130,Number(cfg.coreSize||100)));document.documentElement.style.setProperty('--jarvis-core-scale',String(size/100));document.documentElement.style.setProperty('--jarvis-motion',String(motionMap[cfg.motion]||1));const out=$('#coreSizeValue');if(out)out.value=size+'%';const rng=$('#coreSize');if(rng&&Number(rng.value)!==size)rng.value=String(size);$$('.core-presets button').forEach(b=>b.classList.toggle('on',Number(b.dataset.size)===size));$$('.motion-choice button').forEach(b=>b.classList.toggle('on',b.dataset.motion===cfg.motion))}
function renderDraft(){document.documentElement.dataset.theme=draft.theme;document.documentElement.style.setProperty('--a',themeMap[draft.theme]);applyCoreTuning(draft);$$('.theme').forEach(b=>b.classList.toggle('active',b.dataset.theme===draft.theme));$$('.setting').forEach(s=>{const key=s.dataset.setting;s.querySelectorAll('.choice button').forEach(b=>b.classList.toggle('on',draft.blocks[key]===b.dataset.v))});$$('.orbit-toggle').forEach(b=>b.classList.toggle('on',draft.orbit[b.dataset.orbitKey]!==false))}
$$('.setting').forEach(s=>s.querySelectorAll('.choice button').forEach(b=>b.onclick=()=>{draft.blocks[s.dataset.setting]=b.dataset.v;markDirty();renderDraft()}));
if(orbitSelect)orbitSelect.addEventListener('click',e=>{const b=e.target.closest('.orbit-toggle');if(!b)return;const k=b.dataset.orbitKey;draft.orbit[k]=draft.orbit[k]===false;markDirty();renderDraft()});
$('#coreSize')?.addEventListener('input',e=>{draft.coreSize=Number(e.target.value);markDirty();renderDraft()});$$('.core-presets button').forEach(b=>b.onclick=()=>{draft.coreSize=Number(b.dataset.size);markDirty();renderDraft()});$$('.motion-choice button').forEach(b=>b.onclick=()=>{draft.motion=b.dataset.motion;markDirty();renderDraft()});
const priority={activity:100,events:95,openings:90,presence:80,security:70,sentinel:68,energy:60,climate:55,vehicle:50,network:35,voice:30,memory:25};
function arrangeOrbit(){const cards=$$('.orbit-card').filter(el=>!el.classList.contains('off')&&getComputedStyle(el).display!=='none');cards.sort((a,b)=>(priority[b.dataset.orbit]||0)-(priority[a.dataset.orbit]||0));cards.forEach((el,i)=>el.dataset.slot=String(i+1));$$('.orbit-card').filter(el=>el.classList.contains('off')||getComputedStyle(el).display==='none').forEach(el=>el.removeAttribute('data-slot'))}
function applySaved(){document.documentElement.dataset.theme=saved.theme;document.documentElement.style.setProperty('--a',themeMap[saved.theme]);applyCoreTuning(saved);$$('#homeBlocks [data-block]').forEach(el=>{el.style.display=saved.blocks[el.dataset.block]==='under'?'block':'none'});$$('.orbit-card').forEach(el=>el.classList.toggle('off',saved.orbit[el.dataset.orbit]===false));arrangeOrbit();renderMenuOnly()}
function renderMenuOnly(){const wrap=$('#menuOnly'),grid=$('#menuOnlyGrid');grid.innerHTML='';const labels={energy:'☀️ Solaire',home:'⌂ Maison',export:'⇄ Export / Import',security:'🛡 Sécurité'};Object.keys(saved.blocks).filter(k=>saved.blocks[k]==='menu').forEach(k=>{const d=document.createElement('div');d.className='menuonly-item';d.textContent=labels[k];grid.appendChild(d)});wrap.style.display=grid.children.length?'block':'none'}
$('#saveBtn').onclick=()=>{saved={...clone(draft),activeMenu:saved.activeMenu};persist();dirty=false;$('#saveBtn').classList.remove('dirty');applySaved();const m=$('#savedMsg');m.textContent='✓ Réglages enregistrés';m.classList.add('show');setTimeout(()=>m.classList.remove('show'),1800)};
$('#resetBtn').onclick=()=>{draft={...clone(DEFAULTS),activeMenu:saved.activeMenu};markDirty();renderDraft()};
function updateClock(){const c=$('#liveClock');if(c)c.textContent='MAJ '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}updateClock();setInterval(updateClock,1000);
function syncOrientation(){document.body.classList.toggle('landscape',innerWidth>innerHeight);requestAnimationFrame(arrangeOrbit)}syncOrientation();addEventListener('resize',syncOrientation);addEventListener('orientationchange',()=>setTimeout(syncOrientation,120));

/* State demo: lets the landscape motion be judged without waiting for a real assistant pipeline. */
const stateSeq=[['jarvis-listening','ÉCOUTE'],['jarvis-thinking','RÉFLEXION'],['jarvis-searching','RECHERCHE'],['jarvis-speaking','PAROLE'],['','OPÉRATIONNEL']];let demoTimer=null;
function setDemoState(cls,label){['jarvis-listening','jarvis-thinking','jarvis-searching','jarvis-speaking'].forEach(c=>document.body.classList.remove(c));if(cls)document.body.classList.add(cls);const rd=$('#stateReadout');if(rd)rd.textContent='État : '+label;const st=$('.core .state');if(st)st.textContent=label==='OPÉRATIONNEL'?'EN LIGNE':label}
function runStateDemo(){clearInterval(demoTimer);let i=0;setDemoState(...stateSeq[i]);demoTimer=setInterval(()=>{i=(i+1)%stateSeq.length;setDemoState(...stateSeq[i]);if(i===stateSeq.length-1){clearInterval(demoTimer);setTimeout(()=>setDemoState('','OPÉRATIONNEL'),1100)}},1500)}
$('#stateTest')?.addEventListener('click',runStateDemo);

/* Cinematic boot construction. */
function runBoot(){document.body.classList.add('jarvis-booting');const st=$('.core .state');if(st)st.textContent='INITIALISATION';setTimeout(()=>{if(st)st.textContent='CONSTRUCTION DU CORE'},650);setTimeout(()=>{document.body.classList.remove('jarvis-booting');if(st)st.textContent='EN LIGNE'},2150)}
window.jarvisArrangeOrbit=arrangeOrbit;window.jarvisApplySaved=applySaved;window.jarvisRunBoot=runBoot;window.jarvisRunStateDemo=runStateDemo;
setMenu(saved.activeMenu||'home');renderDraft();applySaved();requestAnimationFrame(()=>setTimeout(runBoot,120));