const DEFAULTS={theme:'classic',blocks:{energy:'under',home:'under',export:'under',security:'under'},orbit:{energy:true,voice:true,security:true,memory:true,sentinel:true,network:true},activeMenu:'home'};
const clone=o=>JSON.parse(JSON.stringify(o));
let saved=clone(DEFAULTS);try{const x=JSON.parse(localStorage.getItem('jarvis_v41_preview')||'null');if(x)saved={...clone(DEFAULTS),...x,blocks:{...DEFAULTS.blocks,...(x.blocks||{})},orbit:{...DEFAULTS.orbit,...(x.orbit||{})}}}catch(e){}
let draft=clone(saved),dirty=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const themeMap={classic:'#00eaff',holo:'#4a8dff',sentinel:'#ff8b36',glass:'#b36cff',neural:'#42ffd6'};
const themeNames={classic:'Classic HUD',holo:'Holo Grid',sentinel:'Sentinel Tactical',glass:'Glass Orbital',neural:'Neural Core'};
const ticks=$('#ticks');for(let i=0;i<72;i++){const e=document.createElement('i');e.className='tick'+(i%6===0?' major':'');e.style.transform=`rotate(${i*5}deg) translateY(-176px)`;ticks.appendChild(e)}
const open=id=>$('#'+id).classList.add('open');const close=id=>$('#'+id).classList.remove('open');
$('#openMenu').onclick=()=>open('menuPanel');$('#menuBtn').onclick=()=>open('menuPanel');$('#settingsBtn').onclick=()=>open('settingsPanel');$('#appearanceBtn').onclick=()=>{open('settingsPanel');selectPane('core')};$('#voiceBtn').onclick=()=>{open('settingsPanel');selectPane('voice')};$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
function selectPane(name){$$('#settingsNav button').forEach(x=>x.classList.toggle('active',x.dataset.pane===name));$$('.settings-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===name))}$$('#settingsNav button').forEach(b=>b.onclick=()=>selectPane(b.dataset.pane));
function persist(){localStorage.setItem('jarvis_v41_preview',JSON.stringify(saved))}
function setMenu(cat){saved.activeMenu=cat;persist();$$('#menuTabs button').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));$$('#menuCards .card').forEach(c=>c.hidden=c.dataset.cat!==cat);renderMenuOnly()}$$('#menuTabs button').forEach(b=>b.onclick=()=>setMenu(b.dataset.cat));
const themesBox=$('#themes');Object.keys(themeMap).forEach(k=>{const b=document.createElement('button');b.className='theme';b.dataset.theme=k;b.innerHTML=`<div class="preview"></div><strong>${themeNames[k]}</strong>`;b.onclick=()=>{draft.theme=k;markDirty();renderDraft()};themesBox.appendChild(b)});
function markDirty(){dirty=true;$('#saveBtn').classList.add('dirty')}
function renderDraft(){document.documentElement.dataset.theme=draft.theme;document.documentElement.style.setProperty('--a',themeMap[draft.theme]);$$('.theme').forEach(b=>b.classList.toggle('active',b.dataset.theme===draft.theme));$$('.setting').forEach(s=>{const key=s.dataset.setting;s.querySelectorAll('.choice button').forEach(b=>b.classList.toggle('on',draft.blocks[key]===b.dataset.v))});$$('.orbit-toggle').forEach(b=>b.classList.toggle('on',!!draft.orbit[b.dataset.orbitKey]))}
$$('.setting').forEach(s=>s.querySelectorAll('.choice button').forEach(b=>b.onclick=()=>{draft.blocks[s.dataset.setting]=b.dataset.v;markDirty();renderDraft()}));
$$('.orbit-toggle').forEach(b=>b.onclick=()=>{const k=b.dataset.orbitKey;draft.orbit[k]=!draft.orbit[k];markDirty();renderDraft()});
function applySaved(){document.documentElement.dataset.theme=saved.theme;document.documentElement.style.setProperty('--a',themeMap[saved.theme]);$$('#homeBlocks [data-block]').forEach(el=>{el.style.display=saved.blocks[el.dataset.block]==='under'?'block':'none'});$$('.orbit-card').forEach(el=>el.classList.toggle('off',!saved.orbit[el.dataset.orbit]));renderMenuOnly()}
function renderMenuOnly(){const wrap=$('#menuOnly'),grid=$('#menuOnlyGrid');grid.innerHTML='';const labels={energy:'☀️ Solaire',home:'⌂ Maison',export:'⇄ Export / Import',security:'🛡 Sécurité'};Object.keys(saved.blocks).filter(k=>saved.blocks[k]==='menu').forEach(k=>{const d=document.createElement('div');d.className='menuonly-item';d.textContent=labels[k];grid.appendChild(d)});wrap.style.display=grid.children.length?'block':'none'}
$('#saveBtn').onclick=()=>{saved={...clone(draft),activeMenu:saved.activeMenu};persist();dirty=false;$('#saveBtn').classList.remove('dirty');applySaved();const m=$('#savedMsg');m.textContent='✓ Réglages enregistrés';m.classList.add('show');setTimeout(()=>m.classList.remove('show'),1800)};
$('#resetBtn').onclick=()=>{draft={...clone(DEFAULTS),activeMenu:saved.activeMenu};markDirty();renderDraft()};
setMenu(saved.activeMenu||'home');renderDraft();applySaved();