(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const left=$('.sidehud.left'),right=$('.sidehud.right');if(!right||!left)return;
right.insertAdjacentHTML('afterbegin',`<div class="sidebox orbit-card context-card" data-orbit="activity"><div class="activity-title"><b>JARVIS</b><span class="activity-state">PARLE</span></div><span class="activity-text">« J’ai vérifié la maison, tout est normal. »</span><div class="activity-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div>`);
left.insertAdjacentHTML('beforeend',`<div class="sidebox orbit-card event-card" data-orbit="events" data-level="info" id="contextEvent"><span class="context-badge">AUTO</span><div class="event-head"><b>INFO CONTEXTUELLE</b><span class="event-age">MAINTENANT</span></div><strong id="eventTitle">Aucune alerte</strong><small id="eventDetail">JARVIS affichera ici l’information prioritaire du moment.</small><div class="event-bar"></div></div>`);
document.body.insertAdjacentHTML('beforeend','<div class="activity-pill"><i></i><span>JARVIS PARLE</span></div><div class="jarvis-statusline"><b>JARVIS</b><small>ÉTAT</small></div><div class="context-summary" id="contextSummary"><b>JARVIS · PRIORITÉ</b><span>Tout est normal.</span></div>');
const select=$('#orbitSelect');if(select){select.insertAdjacentHTML('afterbegin','<button class="orbit-toggle" data-orbit-key="activity"><b>Activité JARVIS</b><small>Écoute / réflexion / parole</small></button><button class="orbit-toggle" data-orbit-key="events"><b>Infos contextuelles</b><small>Alertes / événements prioritaires</small></button>')}
const arrange=()=>requestAnimationFrame(()=>window.jarvisArrangeOrbit?.());
window.jarvisApplySaved?.();
const states={listening:{cls:'jarvis-listening',label:'ÉCOUTE',text:'Je vous écoute…',status:'MICRO ACTIF'},thinking:{cls:'jarvis-thinking',label:'RÉFLÉCHIT',text:'Analyse de votre demande…',status:'ANALYSE EN COURS'},searching:{cls:'jarvis-searching',label:'RECHERCHE',text:'Recherche et vérification en cours…',status:'RECHERCHE ACTIVE'},speaking:{cls:'jarvis-speaking',label:'PARLE',text:'« J’ai vérifié la maison, tout est normal. »',status:'RÉPONSE VOCALE'}};const card=$('.context-card'),pill=$('.activity-pill'),statusline=$('.jarvis-statusline');let timer;
window.jarvisActivity=(state,text)=>{Object.values(states).forEach(s=>document.body.classList.remove(s.cls));clearTimeout(timer);if(!state||!states[state]){card?.classList.remove('active');pill?.classList.remove('show');statusline?.classList.remove('show');const st=$('.state');if(st)st.textContent='EN LIGNE';arrange();return}const s=states[state];document.body.classList.add(s.cls);if(card){card.classList.add('active');card.querySelector('.activity-state').textContent=s.label;card.querySelector('.activity-text').textContent=text||s.text}if(pill){pill.classList.add('show');pill.querySelector('span').textContent='JARVIS '+s.label}if(statusline){statusline.classList.add('show');statusline.querySelector('b').textContent='JARVIS '+s.label;statusline.querySelector('small').textContent=s.status}const st=$('.state');if(st)st.textContent=s.label;arrange();if(state==='speaking')timer=setTimeout(()=>window.jarvisActivity(null),6000)};
const eventCard=$('#contextEvent'),eventTitle=$('#eventTitle'),eventDetail=$('#eventDetail'),summary=$('#contextSummary');let eventTimer;
window.jarvisContextEvent=(type,title,detail,level='info',duration=7000)=>{clearTimeout(eventTimer);if(!eventCard)return;eventCard.dataset.level=level;eventCard.classList.add('event-active');eventTitle.textContent=title||'Information';eventDetail.textContent=detail||'';const age=eventCard.querySelector('.event-age');if(age)age.textContent='MAINTENANT';if(summary){summary.classList.add('show');summary.querySelector('span').textContent=title+(detail?' · '+detail:'')}if(type==='door'){eventCard.querySelector('.event-head b').textContent='OUVERTURE'}else if(type==='presence'){eventCard.querySelector('.event-head b').textContent='PRÉSENCE'}else if(type==='energy'){eventCard.querySelector('.event-head b').textContent='ÉNERGIE'}else if(type==='security'){eventCard.querySelector('.event-head b').textContent='SÉCURITÉ'}else{eventCard.querySelector('.event-head b').textContent='INFO CONTEXTUELLE'}arrange();if(duration>0)eventTimer=setTimeout(()=>{eventCard.classList.remove('event-active');eventCard.dataset.level='info';eventCard.querySelector('.event-head b').textContent='INFO CONTEXTUELLE';eventTitle.textContent='Aucune alerte';eventDetail.textContent='JARVIS affichera ici l’information prioritaire du moment.';summary?.classList.remove('show');arrange()},duration)};
const demoBtn=document.querySelector('.header .headbtn:last-child');if(demoBtn){const seq=['listening','thinking','searching','speaking'];let i=0;demoBtn.title='Démo états JARVIS';demoBtn.onclick=()=>{window.jarvisActivity(seq[i%seq.length]);i++}}
if(eventCard){const events=[['door','Porte garage ouverte','Ouverte depuis 2 min','notice'],['presence','Inès est rentrée','Présence détectée à la maison','info'],['energy','Surplus solaire disponible','2,6 kW exportés actuellement','info'],['security','Mouvement au portail','Sentinelle a détecté une présence','critical']];let j=0;eventCard.style.cursor='pointer';eventCard.onclick=()=>{const e=events[j%events.length];window.jarvisContextEvent(...e);j++}}
arrange();
})();